Remove if-statement from macros
Breaks everything:
[..]
error: /builddir/build/SPECS/kf5-kbookmarks.spec: line 53: %endif with no %if
error: /usr/lib/rpm/redhat/macros: line 368: Macro %else has empty body
error: /usr/lib/rpm/redhat/macros: line 371: Macro %endif has empty body
[..]

Signed-off-by: David Abdurachmanov <davidlt@rivosinc.com>
Signed-off-by: Liu Yang <Yang.Liu.sn@gmail.com>